name: Regression Tests

on:
  push:
    branches:
      - master

  schedule:
    - cron: '2 14 * * *'

  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'

      - name: Run Regression Tests
        run: mvn test